### ISSUE TITLE
Crash - after editing items, and tapping from shopping cart - Keepy

### ISSUE THREAD

**Issue by Debysh** [printdotio/printio-android-sdk#149] opened 2015-10-19 19:09 UTC
Short description: Crash after editing items, saving to shoppingcart and tapping from shopping cart (was able to reproduce with magnets and coasters, should be tested with additional products). Testing using Android 4.4.4
Steps to reproduce:
1. Select > Metal Magnets product > Create it
2. Select 2 items > "next"
3. double tap > zoom > save (first item)
4. double tap > rotate > save (second item)
5. save to shopping cart
6. tap on thumbnail from shopping cart

**Comment by tobiasfrier** [comment] 2015-10-19 20:17
@Debysh We will be trying to reproduce this on Android 4.4.4 as well as other versions. I was unable to reproduce this on a Galaxy S5 running Android 5.0

**Comment by vladopajic** [comment] 2015-10-20 11:21
Hello @Debysh,

Could you supply us with crash log and version of used SDK? 

Thanks,
Vlado

**Comment by ivankovicmilos** [comment] 2015-10-20 11:24
Hi, @Debysh 

I tried to reproduce this crash on my devices (Nexus 5, Samsung S5 and HTC One X) and I could not recreate it.
Can you send us which devices are used for testing and inicialization code?

Thanks,
Milos

**Comment by Debysh** [comment] 2015-10-20 17:56
Hi Milos, Vlado and Tobias,

I am able to reproduce this crash only on Nexus 4, running Android 4.4.4.
I have a log file that I tried to attach here - but I got : "Attaching documents requires write permission to this repository" message - please advise.
Deby

**Comment by ivankovicmilos** [comment] 2015-10-20 18:14
@Debysh 

You can provide log via email. And please, send to us initialization code.

vlado@makeable.com, milosi@makeable.com, tobias@makeable.com

**Comment by bomberaya** [comment] 2015-12-23 10:43
Fixed in v3.1.27

**Closed by bomberaya** 2015-12-23 10:43 UTC
Labels: bug
