### ISSUE TITLE
Medium/High: Our phone case promo shows an error when loading product details

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#128] opened 2015-04-03 03:36 UTC
Newest sdk, all devices. 

Our phone case promo stopped working with the newest sdk versions. Did the product ID for phone cases change?

Also, can we change the message for errors like these? 

![screenshot_2015-04-02-21-03-49](https://cloud.githubusercontent.com/assets/8051364/6977689/14372716-d980-11e4-8811-b30e01f90100.png)

**Comment by AustenB** [comment] 2015-04-03 04:16
Can you provide more details?

How did this used to work? What step did you see this on?

This screen typically means problem connecting to server.

**Comment by itscam** [comment] 2015-04-04 00:40
@AustenB @bomberaya We have a hard-coded promo on our home screen. After tapping on this, the print sdk opens to the phone case product. The newer SDK versions do not open to the phone case product, but instead show the error. 

![screenshot_2015-04-03-16-04-53](https://cloud.githubusercontent.com/assets/8051364/6990734/95e3b530-da30-11e4-9f1f-fa7399b1ba0a.png)

**Comment by AustenB** [comment] 2015-04-04 00:52
Got it. Send the code that we launch from that promo if you can.

Thank you will get it fixed asap

**Comment by wrightcode** [comment] 2015-04-06 16:49
The code to launch the PrintShop fragment has already been sent to Bojan.  It's launched via an intent with these variables:

Promo code "CALLME50" 

and the product id PublicConstants.ProductIds.PHONE_CASES

With the latest apk, you should be able to click on the promo banner (in Cam's screen shot above) and test.

What other specific information do you need?

**Comment by bomberaya** [comment] 2015-04-07 19:28
@wrightcode We cannot reproduce this, I tried using your initialization code with your live RECIPE_ID.

Can you try using ```PIOConfig.setProductIdFromApp()``` and ```PIOConfig.setPromoCode()``` separately?
Do they work as expected?

Can you try logging the ProductID that you are passing to ```PIOConfig.setProductIdFromApp()```?

**Comment by wrightcode** [comment] 2015-04-07 20:32
The value we're using to set the productIdFromApp() is:  

PublicConstants.ProductIds.PHONE_CASES

And when I debug this, it looks like this value is 0.

Can you check the value of this variable and see if it's changed?  It looks like it use to be > 0.

**Comment by AustenB** [comment] 2015-04-07 20:34
product id for phone cases should be: 57

On Tue, Apr 7, 2015 at 4:32 PM, Jay Wright <notifications@github.com> wrote:

> The value we're using to set the productIdFromApp() is:
>
> PublicConstants.ProductIds.PHONE_CASES
>
> And when I debug this, it looks like this value is 0.
>
> Can you check the value of this variable and see if it's changed? It looks
> like it use to be > 0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/128#issuecomment-90722910>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by wrightcode** [comment] 2015-04-07 20:36
Thanks, that's consistent with what we're seeing in our production app.  But since pulling the latest print io tag, that value is now 0.  

@bomberaya could the value in print.io.PublicConstants.ProductIds.PHONE_CASES have changed?

**Comment by AustenB** [comment] 2015-04-07 20:37
Jay:

You should pull product id's from our API if possible.

Best,

Austen

On Tue, Apr 7, 2015 at 4:36 PM, Jay Wright <notifications@github.com> wrote:

> Thanks, that's consistent with what we're seeing in our production app.
> But since pulling the latest print io tag, that value is now 0.
>
> @bomberaya <https://github.com/bomberaya> could the value in
> print.io.PublicConstants.ProductIds.PHONE_CASES have changed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/128#issuecomment-90724089>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by bomberaya** [comment] 2015-04-07 20:38
@wrightcode These "Constants" are not really constants. They are initialized at runtime based on staging/live setting in SDK. This initialization method is called inside ```PIOConfig.setLiveApplication()``` method. The initialization seems to be failing for some reason. Could be related to ProGuard. I will investigate.

**Comment by bomberaya** [comment] 2015-04-07 20:45
@wrightcode Do you perform any additional ProGuard obfuscation on your test builds?

**Comment by wrightcode** [comment] 2015-04-07 20:46
@bomberaya Thanks.  It looks like we use to call PIO.setLiveApplication() in our Application object, but now it's been moved to the same fragment where we launch Print IO.  Could it not initialize quickly enough.

**Comment by wrightcode** [comment] 2015-04-07 20:47
@bomberaya We're not doing any additional ProGaurd obfuscation.

**Comment by bomberaya** [comment] 2015-04-07 20:49
@wrightcode Not initializing quickly enough is out of question since the method is synchronous (and I guess you are not doing the initialization in a separate thread)

**Comment by wrightcode** [comment] 2015-04-07 20:53
@bomberaya Okay, cool.  You're right, we're not doing anything special with threads.  Glad to hear its synchronous.

**Comment by bomberaya** [comment] 2015-04-07 20:54
@wrightcode I will try to figure out why the values become 0

**Comment by bomberaya** [comment] 2015-04-07 21:09
@wrightcode Can you check the logs and see if there is a line that says: "PIO config restored: (successfully/unsuccessfully)"?

**Comment by wrightcode** [comment] 2015-04-07 21:11
@bomberaya I see these:
04-07 15:11:14.534  29678-29678/com.photobucket.android D/PictureApp﹕ [PIO] PIO config stored: successfully
04-07 15:11:14.554  29678-29678/com.photobucket.android D/PictureApp﹕ [PIO] PIO SDK is starting...

**Comment by wrightcode** [comment] 2015-04-07 21:13
@bomberaya and I see some warnings about some print io related files it cannot find.

**Comment by bomberaya** [comment] 2015-04-07 21:15
@wrightcode The log entries are ok. If you are on a "clean" installation (or shopping cart is empty) and you get a warning that the shopping cart file does not exist, that is also ok.

**Comment by wrightcode** [comment] 2015-04-07 21:15
@bomberaya But I don't see 'restored', only 'stored'.

**Comment by wrightcode** [comment] 2015-04-07 21:16
@bomberaya Okay, good to know.  Yes, we're running a clean installation each time we test this bug.

**Comment by bomberaya** [comment] 2015-04-07 21:36
@wrightcode I will add the following statement at the end of `initProductIds()` method:
```java
LOG.d("Acrylic Prints ProductID:"+PublicConstants.ProductIds.ACRYLIC_PRINTS);
```

I picked Acrylic Prints as an example because it has different IDs on staging and live.
This way we will be able to tell if the product id is 0 or corresponding staging/live value.
I can send you an unofficial PIO jar with this modification.
I'm trying to figure out where exactly the values become zero.

**Comment by wrightcode** [comment] 2015-04-07 21:41
@bomberaya Yeah, send me the jar and I'll let you know what the value is.  Just so you know we're using the live server, not staging for our tests.

**Comment by wrightcode** [comment] 2015-04-08 21:56
@bomberaya So I think I know what's going on.

Our PrintFragment instantiates the PIOConfig, which in turn calls initProductIds, which is fine.

However, we start that fragment with an intent and one of the extras in that intent is PublicConstants.ProductIds.PRODUCT_CASES.

So we're accessing that "constant" before PIOConfig is initialized.

PIOConfig isn't a singleton, right?  
Do I need to initialize it in the fragment that configures the intent to start the fragment that initializes PIO?


```
    PIOConfig pioConfig = new PIOConfig();
    pioConfig.setLiveApplication(PbApplication.PRINTIO_IS_LIVE_APP);

    // Launch the PrintIO SDK Fragment
    Intent intent = new Intent( <snip>
    Bundle bundle = new Bundle();
    bundle.putInt(INTENT_KEY_PRODUCT_ID,
                        PublicConstants.ProductIds.PHONE_CASES);
    <snip>
    intent.putExtras(bundle);
    startActivity(intent);
                
```

Is that a proper use of that class?  Is that too much overhead just to populate those productIds?

**Comment by vladopajic** [comment] 2015-04-09 12:33
@wrightcode Hay, you got it all right. :)

PIOConfig is not singleton. Intention of introducing PIOConfig was to isolate entire PIO SDK configuration in non-singleton object rather then holding it in static fields of PIO class which holds other SDK mechanisms.

Yes, it is an overhead to do that just to populate public ids, but that's what you'll need to do for now. In next release, we will replace PublicConstants.ProductIds with an enum so you (as our SDK user) will not need to worry about value of product id.

**Comment by wrightcode** [comment] 2015-04-09 15:16
Great, will that be in PIO SDK v2.1.8?

**Comment by bomberaya** [comment] 2015-04-09 15:17
@wrightcode I think so, let's set v2.1.8 as a milestone for this

**Comment by bomberaya** [comment] 2015-04-10 15:19
@wrightcode We switched from using raw ProductIDs to enums. Please check out the MIGRATION_GUIDE document for info on how to upgrade from v2.x to v2.1.8.

This should prevent similar issues from happening in the future.

**Comment by wrightcode** [comment] 2015-04-10 17:09
@bomberaya Is ProductType serializable / parcelable?  I need to pass these values as an intent extra.  Also, is there a ProductType enum value for NONE or UNSPECIFIED?

**Comment by vladopajic** [comment] 2015-04-10 17:57
@wrightcode ProductType is serializable / parcelable. 
Howerver, there is no NONE nor UNSPECIFIED values in this enum, as purpose of this enum is to hold values of all product types. You will have to deal with unspecified product on your side on your own (probably you should pass null as intent extra).

**Comment by wrightcode** [comment] 2015-04-13 17:21
Is there a way to get the proper ProductType from an integer productId value?  

For example, if we're using productId 102 in a marketing campaign, I need a reliable way for ProductType to return me the proper ProductType (MAGNETS, for example).  

Maybe this functionality already exists.

**Comment by wrightcode** [comment] 2015-04-13 17:45
And can someone confirm which ProductType has productId 102?  (We're running a promo on magnets)

**Comment by AustenB** [comment] 2015-04-13 17:47
This product is called Magnetgram

Product Category Photo Gifts
Is that what you mean? How is ProductType Used in SDK?

On Mon, Apr 13, 2015 at 1:45 PM, Jay Wright <notifications@github.com>
wrote:

> And can someone confirm which ProductType has productId 102? (We're
> running a promo on magnets)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/128#issuecomment-92443049>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by wrightcode** [comment] 2015-04-13 17:49
Magnetgram is the answer I'm looking for in the second question, thank you.  

ProductType is a new Enum class in the SDK so hopefully @bomberaya or @vladopajic can address the technical aspect of my first question.

**Comment by AustenB** [comment] 2015-04-13 17:50
Jay.

This is all accessible in our admin panel as well as via our API.

Katie and Shawna can create a user account for you -> this should make
things even easier :)

Austen

On Mon, Apr 13, 2015 at 1:49 PM, Jay Wright <notifications@github.com>
wrote:

> Magnetgram is the answer I'm looking for in the second question, thank
> you.
>
> ProductType is a new Enum class in the SDK so hopefully @bomberaya
> <https://github.com/bomberaya> or @vladopajic
> <https://github.com/vladopajic> can address the technical aspect of my
> first question.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/128#issuecomment-92443906>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by vladopajic** [comment] 2015-04-14 10:37
@wrightcode Hey :)

ProductType enum values have two methods which return live or staging ID of the product (getLiveId() and getStagingId() respectively). You should use them to check actual value of product ID. 

We currently do not have any method which will return ProductType for corresponding integer product ID. For not you will have to do it on your own using above way of getting actual values of product IDs.

**Comment by AustenB** [comment] 2015-04-14 13:54
You can use our public api for it

**Comment by wrightcode** [comment] 2015-04-14 14:45
@vladopajic @bomberaya I can certainly iterate the Enum and use those values, but if you wanted to encapsulate it in the ProductType enum, that'd be cool.  I was thinking something like:

```
    public ProductType getProductType(int id) {
        // defaults to live
        return getProductType(id, true);
    }
    
    public ProductType getProductType(int id, boolean isLive) {
        // return proper ProductType based on id, live/staging boolean
        // or if not valid id, return null
        return null;
    }
```

But for now I'll write our own util function for that.

**Comment by bomberaya** [comment] 2015-04-14 14:47
@wrightcode We will definitely add a helper method for that :+1:

**Comment by bomberaya** [comment] 2015-04-14 15:12
@wrightcode Created new ticket #132

**Comment by wrightcode** [comment] 2015-04-14 15:19
@bomberaya excellent thanks!  appreciate it.

**Comment by bomberaya** [comment] 2015-04-14 15:20
@wrightcode Has this one been fixed? Can we close ticket 128?

**Comment by wrightcode** [comment] 2015-04-14 16:57
@itscam  i believe this one is fixed.

**Comment by bomberaya** [comment] 2015-04-14 17:04
@wrightcode Thanks! Closing :)

**Closed by bomberaya** 2015-04-14 17:04 UTC
Labels: bug, Ready to Test
