### ISSUE TITLE
Missing images for Minibook (Photobucket)

### ISSUE THREAD

**Issue by tamaratomovski** [printdotio/printio-android-sdk#126] opened 2015-03-29 09:35 UTC
We have a PB order for a minibook whose images didn't generate well. Namely, from the 60th picture until the end there are no images, it's blank and when I open manipulation command there is no link to the image.

Could you please look into this?

Thank you!

@AustenB  @Ivan1985  @bomberaya 

Order: https://admin-v2.print.io/Home#/orders/154369/images

Item: 393982

![minibk](https://cloud.githubusercontent.com/assets/10880662/6884887/92392b64-d606-11e4-9827-4a2c6399975a.png)

**Comment by bomberaya** [comment] 2015-04-02 11:07
This is a duplicate of #120 which has been fixed in v2.0.3

**Closed by bomberaya** 2015-04-02 11:07 UTC
Labels: bug, question
